<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DiscordRamLimiter</RootNamespace>
    <AssemblyName>KeepItDigitalRamLimiter</AssemblyName>
    <ApplicationIcon>Assets\keepitdigital.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**;artifacts\**;publish\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\administrator-panel.gif" />
    <Resource Include="Assets\keepitdigital.png" />
  </ItemGroup>
</Project>
